

//#ifndef EXTERN_EMEA_H
//#define EXTERN_EMEA_H

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif


/******************************************************************
						Bitel Header Files
********************************************************************/

#include "../BF_SDK/include/BTEMEA_LIB/LCD_UI.h"
#include "../BF_SDK/include/BTEMEA_LIB/LCD.h"
#include "../BF_SDK/include/BTEMEA_LIB/message.h"
#include "../BF_SDK/include/BTEMEA_LIB/MEMREG.h"
#include "../BF_SDK/include/BTEMEA_LIB/TCP.h"
#include "../BF_SDK/include/BTEMEA_LIB/GPRS.h"
#include "../BF_SDK/include/BTEMEA_LIB/WIFI.h"
#include "../BF_SDK/include/BTEMEA_LIB/KEYPAD.h"
#include "../BF_SDK/include/BTEMEA_LIB/MSR.h"
#include "../BF_SDK/include/BTEMEA_LIB/RFID.h"
#include "../BF_SDK/include/BTEMEA_LIB/ARABIC.h"
#include "../BF_SDK/include/BTEMEA_LIB/PRINT.h"
#include "../BF_SDK/include/BTEMEA_LIB/ICCARD.h"
#include "../BF_SDK/include/BTEMEA_LIB/triple_des.h"

#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/aes.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/arc4.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/base64.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/bignum.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/bn_mul.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/camellia.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/certs.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/config.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/debug.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/des.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/dhm.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/havege.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/md2.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/md4.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/md5.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/net.h"
//#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/openssl.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/padlock.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/rsa.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/sha1.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/sha2.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/sha4.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/ssl.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/timing.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/version.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/x509.h"
#include "../BF_SDK/INCLUDE/BTEMEA_LIB/ssl/xtea.h"

#ifdef __cplusplus
}
#endif




//#endif

/* */
