
/*======================================================================*/
/*																		*/
/*								LCDFONTC.H								*/
/*																		*/
/*======================================================================*/

extern const char RomanLcdFont[];	/* ISO8859-1 RomanFont */
extern const char OtherLcdFont[];	/* ISO8859-6 Farsi Font */
extern const char eprcs[];	/* ISO8859-6 Farsi Font */
extern const char BoldFont[];	/* ISO8859-6 Farsi Font */
extern const char DefaultFONT[];	/* ISO8859-6 Farsi Font */

/* */
