/* BM_C_SoapClient.c
   Generated by gSOAP 2.8.19 from BM_WSDL_C.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "BM_C_SoapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) BM_C_SoapClient.c ver 2.8.19 2014-11-27 12:44:13 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ExecuteTransaction(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ExecuteTransaction *ns1__ExecuteTransaction, struct _ns1__ExecuteTransactionResponse *ns1__ExecuteTransactionResponse)
{	struct __ns1__ExecuteTransaction soap_tmp___ns1__ExecuteTransaction;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/ExecuteTransaction";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ExecuteTransaction.ns1__ExecuteTransaction = ns1__ExecuteTransaction;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__ExecuteTransaction(soap, &soap_tmp___ns1__ExecuteTransaction);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ExecuteTransaction(soap, &soap_tmp___ns1__ExecuteTransaction, "-ns1:ExecuteTransaction", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ExecuteTransaction(soap, &soap_tmp___ns1__ExecuteTransaction, "-ns1:ExecuteTransaction", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ExecuteTransactionResponse)
		return soap_closesock(soap);
	soap_default__ns1__ExecuteTransactionResponse(soap, ns1__ExecuteTransactionResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__ExecuteTransactionResponse(soap, ns1__ExecuteTransactionResponse, "ns1:ExecuteTransactionResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SendSettlement(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__SendSettlement *ns1__SendSettlement, struct _ns1__SendSettlementResponse *ns1__SendSettlementResponse)
{	struct __ns1__SendSettlement soap_tmp___ns1__SendSettlement;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/SendSettlement";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SendSettlement.ns1__SendSettlement = ns1__SendSettlement;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__SendSettlement(soap, &soap_tmp___ns1__SendSettlement);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SendSettlement(soap, &soap_tmp___ns1__SendSettlement, "-ns1:SendSettlement", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SendSettlement(soap, &soap_tmp___ns1__SendSettlement, "-ns1:SendSettlement", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SendSettlementResponse)
		return soap_closesock(soap);
	soap_default__ns1__SendSettlementResponse(soap, ns1__SendSettlementResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__SendSettlementResponse(soap, ns1__SendSettlementResponse, "ns1:SendSettlementResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DBChecker(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__DBChecker *ns1__DBChecker, struct _ns1__DBCheckerResponse *ns1__DBCheckerResponse)
{	struct __ns1__DBChecker soap_tmp___ns1__DBChecker;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/DBChecker";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DBChecker.ns1__DBChecker = ns1__DBChecker;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__DBChecker(soap, &soap_tmp___ns1__DBChecker);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DBChecker(soap, &soap_tmp___ns1__DBChecker, "-ns1:DBChecker", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DBChecker(soap, &soap_tmp___ns1__DBChecker, "-ns1:DBChecker", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DBCheckerResponse)
		return soap_closesock(soap);
	soap_default__ns1__DBCheckerResponse(soap, ns1__DBCheckerResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__DBCheckerResponse(soap, ns1__DBCheckerResponse, "ns1:DBCheckerResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpdateSignature(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__UpdateSignature *ns1__UpdateSignature, struct _ns1__UpdateSignatureResponse *ns1__UpdateSignatureResponse)
{	struct __ns1__UpdateSignature soap_tmp___ns1__UpdateSignature;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/UpdateSignature";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UpdateSignature.ns1__UpdateSignature = ns1__UpdateSignature;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__UpdateSignature(soap, &soap_tmp___ns1__UpdateSignature);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UpdateSignature(soap, &soap_tmp___ns1__UpdateSignature, "-ns1:UpdateSignature", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UpdateSignature(soap, &soap_tmp___ns1__UpdateSignature, "-ns1:UpdateSignature", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__UpdateSignatureResponse)
		return soap_closesock(soap);
	soap_default__ns1__UpdateSignatureResponse(soap, ns1__UpdateSignatureResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__UpdateSignatureResponse(soap, ns1__UpdateSignatureResponse, "ns1:UpdateSignatureResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UploadBatch(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__UploadBatch *ns1__UploadBatch, struct _ns1__UploadBatchResponse *ns1__UploadBatchResponse)
{	struct __ns1__UploadBatch soap_tmp___ns1__UploadBatch;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/UploadBatch";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__UploadBatch.ns1__UploadBatch = ns1__UploadBatch;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__UploadBatch(soap, &soap_tmp___ns1__UploadBatch);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__UploadBatch(soap, &soap_tmp___ns1__UploadBatch, "-ns1:UploadBatch", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__UploadBatch(soap, &soap_tmp___ns1__UploadBatch, "-ns1:UploadBatch", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__UploadBatchResponse)
		return soap_closesock(soap);
	soap_default__ns1__UploadBatchResponse(soap, ns1__UploadBatchResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__UploadBatchResponse(soap, ns1__UploadBatchResponse, "ns1:UploadBatchResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Login(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__Login *ns1__Login, struct _ns1__LoginResponse *ns1__LoginResponse)
{	struct __ns1__Login soap_tmp___ns1__Login;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/Login";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Login.ns1__Login = ns1__Login;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__Login(soap, &soap_tmp___ns1__Login);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Login(soap, &soap_tmp___ns1__Login, "-ns1:Login", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Login(soap, &soap_tmp___ns1__Login, "-ns1:Login", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__LoginResponse)
		return soap_closesock(soap);
	soap_default__ns1__LoginResponse(soap, ns1__LoginResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__LoginResponse(soap, ns1__LoginResponse, "ns1:LoginResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CheckUpdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckUpdate *ns1__CheckUpdate, struct _ns1__CheckUpdateResponse *ns1__CheckUpdateResponse)
{	struct __ns1__CheckUpdate soap_tmp___ns1__CheckUpdate;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/CheckUpdate";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CheckUpdate.ns1__CheckUpdate = ns1__CheckUpdate;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__CheckUpdate(soap, &soap_tmp___ns1__CheckUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CheckUpdate(soap, &soap_tmp___ns1__CheckUpdate, "-ns1:CheckUpdate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CheckUpdate(soap, &soap_tmp___ns1__CheckUpdate, "-ns1:CheckUpdate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckUpdateResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckUpdateResponse(soap, ns1__CheckUpdateResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckUpdateResponse(soap, ns1__CheckUpdateResponse, "ns1:CheckUpdateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ReloadService(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ReloadService *ns1__ReloadService, struct _ns1__ReloadServiceResponse *ns1__ReloadServiceResponse)
{	struct __ns1__ReloadService soap_tmp___ns1__ReloadService;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/ReloadService";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ReloadService.ns1__ReloadService = ns1__ReloadService;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__ReloadService(soap, &soap_tmp___ns1__ReloadService);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ReloadService(soap, &soap_tmp___ns1__ReloadService, "-ns1:ReloadService", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ReloadService(soap, &soap_tmp___ns1__ReloadService, "-ns1:ReloadService", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ReloadServiceResponse)
		return soap_closesock(soap);
	soap_default__ns1__ReloadServiceResponse(soap, ns1__ReloadServiceResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__ReloadServiceResponse(soap, ns1__ReloadServiceResponse, "ns1:ReloadServiceResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLogFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetLogFile *ns1__GetLogFile, struct _ns1__GetLogFileResponse *ns1__GetLogFileResponse)
{	struct __ns1__GetLogFile soap_tmp___ns1__GetLogFile;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/GetLogFile";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLogFile.ns1__GetLogFile = ns1__GetLogFile;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLogFile(soap, &soap_tmp___ns1__GetLogFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLogFile(soap, &soap_tmp___ns1__GetLogFile, "-ns1:GetLogFile", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLogFile(soap, &soap_tmp___ns1__GetLogFile, "-ns1:GetLogFile", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetLogFileResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetLogFileResponse(soap, ns1__GetLogFileResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetLogFileResponse(soap, ns1__GetLogFileResponse, "ns1:GetLogFileResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetLog *ns1__GetLog, struct _ns1__GetLogResponse *ns1__GetLogResponse)
{	struct __ns1__GetLog soap_tmp___ns1__GetLog;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://41.38.125.23:9003/mPOSHosting.svc/soap";
	if (soap_action == NULL)
		soap_action = "http://tempuri.org/ImPOSService/GetLog";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetLog.ns1__GetLog = ns1__GetLog;
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap_serializeheader(soap);
	soap_serialize___ns1__GetLog(soap, &soap_tmp___ns1__GetLog);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetLog(soap, &soap_tmp___ns1__GetLog, "-ns1:GetLog", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetLog(soap, &soap_tmp___ns1__GetLog, "-ns1:GetLog", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetLogResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetLogResponse(soap, ns1__GetLogResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetLogResponse(soap, ns1__GetLogResponse, "ns1:GetLogResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of BM_C_SoapClient.c */
