/* BM_C_SoapStub.h
   Generated by gSOAP 2.8.19 from BM_WSDL_C.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef BM_C_SoapStub_H
#define BM_C_SoapStub_H
#define SOAP_NAMESPACE_OF_ns2	"http://tempuri.org/Imports"
#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"
#define SOAP_NAMESPACE_OF_ns3	"http://schemas.microsoft.com/2003/10/Serialization/"
#define SOAP_NAMESPACE_OF_ns4	"http://schemas.datacontract.org/2004/07/mPOSServiceInterfaceLib"
#define SOAP_NAMESPACE_OF_ns5	"http://schemas.datacontract.org/2004/07/CommunicationMessages"
#define SOAP_NAMESPACE_OF_ns6	"http://schemas.microsoft.com/Message"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20819
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (11)
/* xsd:boolean */
enum xsd__boolean { xsd__boolean__false_ = 0, xsd__boolean__true_ = 1 };
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
/* Base64 schema type: */
struct xsd__base64Binary
{
	unsigned char *__ptr;
	int __size;
	char *id;	/* optional element of type xsd:string */
	char *type;	/* optional element of type xsd:string */
	char *options;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__ExecuteTransaction
#define SOAP_TYPE__ns1__ExecuteTransaction (23)
/* ns1:ExecuteTransaction */
struct _ns1__ExecuteTransaction
{
	struct ns4__TransactionModel *posModel;	/* optional element of type ns4:TransactionModel */
};
#endif

#ifndef SOAP_TYPE__ns1__ExecuteTransactionResponse
#define SOAP_TYPE__ns1__ExecuteTransactionResponse (26)
/* ns1:ExecuteTransactionResponse */
struct _ns1__ExecuteTransactionResponse
{
	struct ns4__TransactionResponse *ExecuteTransactionResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns4:TransactionResponse */
};
#endif

#ifndef SOAP_TYPE__ns1__SendSettlement
#define SOAP_TYPE__ns1__SendSettlement (29)
/* ns1:SendSettlement */
struct _ns1__SendSettlement
{
	struct ns4__settlement *settlement;	/* optional element of type ns4:settlement */
};
#endif

#ifndef SOAP_TYPE__ns1__SendSettlementResponse
#define SOAP_TYPE__ns1__SendSettlementResponse (32)
/* ns1:SendSettlementResponse */
struct _ns1__SendSettlementResponse
{
	struct ns4__TransactionResponse *SendSettlementResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns4:TransactionResponse */
};
#endif

#ifndef SOAP_TYPE__ns1__DBChecker
#define SOAP_TYPE__ns1__DBChecker (33)
/* ns1:DBChecker */
struct _ns1__DBChecker
{
	struct ns4__SQlModel *model;	/* optional element of type ns4:SQlModel */
};
#endif

#ifndef SOAP_TYPE__ns1__DBCheckerResponse
#define SOAP_TYPE__ns1__DBCheckerResponse (36)
/* ns1:DBCheckerResponse */
struct _ns1__DBCheckerResponse
{
	struct ns4__SQlResponseModel *DBCheckerResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns4:SQlResponseModel */
};
#endif

#ifndef SOAP_TYPE__ns1__UpdateSignature
#define SOAP_TYPE__ns1__UpdateSignature (39)
/* ns1:UpdateSignature */
struct _ns1__UpdateSignature
{
	struct ns4__sig *sig;	/* optional element of type ns4:sig */
};
#endif

#ifndef SOAP_TYPE__ns1__UpdateSignatureResponse
#define SOAP_TYPE__ns1__UpdateSignatureResponse (42)
/* ns1:UpdateSignatureResponse */
struct _ns1__UpdateSignatureResponse
{
	struct ns4__SignatureResponseModel *UpdateSignatureResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns4:SignatureResponseModel */
};
#endif

#ifndef SOAP_TYPE__ns1__UploadBatch
#define SOAP_TYPE__ns1__UploadBatch (45)
/* ns1:UploadBatch */
struct _ns1__UploadBatch
{
	struct ns4__BatchUploadRequest *batchData;	/* optional element of type ns4:BatchUploadRequest */
};
#endif

#ifndef SOAP_TYPE__ns1__UploadBatchResponse
#define SOAP_TYPE__ns1__UploadBatchResponse (48)
/* ns1:UploadBatchResponse */
struct _ns1__UploadBatchResponse
{
	struct ns4__BatchResponseModel *UploadBatchResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns4:BatchResponseModel */
};
#endif

#ifndef SOAP_TYPE__ns1__Login
#define SOAP_TYPE__ns1__Login (51)
/* ns1:Login */
struct _ns1__Login
{
	struct ns4__loginModel *loginModel;	/* optional element of type ns4:loginModel */
};
#endif

#ifndef SOAP_TYPE__ns1__LoginResponse
#define SOAP_TYPE__ns1__LoginResponse (54)
/* ns1:LoginResponse */
struct _ns1__LoginResponse
{
	struct ns4__loginModelResponse *LoginResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns4:loginModelResponse */
};
#endif

#ifndef SOAP_TYPE__ns1__CheckUpdate
#define SOAP_TYPE__ns1__CheckUpdate (57)
/* ns1:CheckUpdate */
struct _ns1__CheckUpdate
{
	struct ns4__loginModel *checkModel;	/* optional element of type ns4:loginModel */
};
#endif

#ifndef SOAP_TYPE__ns1__CheckUpdateResponse
#define SOAP_TYPE__ns1__CheckUpdateResponse (58)
/* ns1:CheckUpdateResponse */
struct _ns1__CheckUpdateResponse
{
	struct ns4__loginModelResponse *CheckUpdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns4:loginModelResponse */
};
#endif

#ifndef SOAP_TYPE__ns1__ReloadService
#define SOAP_TYPE__ns1__ReloadService (59)
/* ns1:ReloadService */
struct _ns1__ReloadService
{
	char *Code;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__ReloadServiceResponse
#define SOAP_TYPE__ns1__ReloadServiceResponse (60)
/* ns1:ReloadServiceResponse */
struct _ns1__ReloadServiceResponse
{
	char *ReloadServiceResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetLogFile
#define SOAP_TYPE__ns1__GetLogFile (61)
/* ns1:GetLogFile */
struct _ns1__GetLogFile
{
	char *Code;	/* optional element of type xsd:string */
	char *Latest;	/* optional element of type xsd:string */
	char *Count;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetLogFileResponse
#define SOAP_TYPE__ns1__GetLogFileResponse (62)
/* ns1:GetLogFileResponse */
struct _ns1__GetLogFileResponse
{
	struct xsd__base64Binary GetLogFileResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns6:StreamBody */
};
#endif

#ifndef SOAP_TYPE__ns1__GetLog
#define SOAP_TYPE__ns1__GetLog (63)
/* ns1:GetLog */
struct _ns1__GetLog
{
	char *data;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetLogResponse
#define SOAP_TYPE__ns1__GetLogResponse (64)
/* ns1:GetLogResponse */
struct _ns1__GetLogResponse
{
	char *GetLogResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__ArrayOfTransactionDataList
#define SOAP_TYPE_ns4__ArrayOfTransactionDataList (65)
/* ns4:ArrayOfTransactionDataList */
struct ns4__ArrayOfTransactionDataList
{
	int __sizeTransactionDataList;	/* sequence of elements <TransactionDataList> */
	struct ns4__TransactionDataList *TransactionDataList;	/* optional element of type ns4:TransactionDataList */
};
#endif

#ifndef SOAP_TYPE_ns4__TransactionDataList
#define SOAP_TYPE_ns4__TransactionDataList (66)
/* ns4:TransactionDataList */
struct ns4__TransactionDataList
{
	char *AuthCode;	/* optional element of type xsd:string */
	char *RRN;	/* optional element of type xsd:string */
	char *STAN;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__SQlModel
#define SOAP_TYPE_ns4__SQlModel (34)
/* ns4:SQlModel */
struct ns4__SQlModel
{
	char *code;	/* optional element of type xsd:string */
	char *script;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__SQlResponseModel
#define SOAP_TYPE_ns4__SQlResponseModel (37)
/* ns4:SQlResponseModel */
struct ns4__SQlResponseModel
{
	int *Code;	/* optional element of type xsd:int */
	char *Message;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__SignatureResponseModel
#define SOAP_TYPE_ns4__SignatureResponseModel (43)
/* ns4:SignatureResponseModel */
struct ns4__SignatureResponseModel
{
	int *Code;	/* optional element of type xsd:int */
	char *Message;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__BatchUploadRequest
#define SOAP_TYPE_ns4__BatchUploadRequest (46)
/* ns4:BatchUploadRequest */
struct ns4__BatchUploadRequest
{
	char *AC;	/* optional element of type xsd:string */
	char *BID;	/* optional element of type xsd:string */
	int *CC;	/* optional element of type xsd:int */
	LONG64 *CRC;	/* optional element of type xsd:long */
	char *CapDate;	/* optional element of type xsd:string */
	char *DATA;	/* optional element of type xsd:string */
	int *HostID;	/* optional element of type xsd:int */
	char *LTime;	/* optional element of type xsd:string */
	char *MID;	/* optional element of type xsd:string */
	int *SEQ;	/* optional element of type xsd:int */
	char *STAN;	/* optional element of type xsd:string */
	int *TC;	/* optional element of type xsd:int */
	char *TID;	/* optional element of type xsd:string */
	struct ns4__ArrayOfTransactionModel *TList;	/* optional element of type ns4:ArrayOfTransactionModel */
	char *Versions;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__ArrayOfTransactionModel
#define SOAP_TYPE_ns4__ArrayOfTransactionModel (71)
/* ns4:ArrayOfTransactionModel */
struct ns4__ArrayOfTransactionModel
{
	int __sizeTransactionModel;	/* sequence of elements <TransactionModel> */
	struct ns4__TransactionModel *TransactionModel;	/* optional element of type ns4:TransactionModel */
};
#endif

#ifndef SOAP_TYPE_ns4__BatchResponseModel
#define SOAP_TYPE_ns4__BatchResponseModel (49)
/* ns4:BatchResponseModel */
struct ns4__BatchResponseModel
{
	int *Code;	/* optional element of type xsd:int */
	int *LastStan;	/* optional element of type xsd:int */
	char *Message;	/* optional element of type xsd:string */
	int *NextChunk;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns4__loginModel
#define SOAP_TYPE_ns4__loginModel (52)
/* ns4:loginModel */
struct ns4__loginModel
{
	char *AppVer;	/* optional element of type xsd:string */
	char *ConfigVer;	/* optional element of type xsd:string */
	char *MID;	/* optional element of type xsd:string */
	char *Pass;	/* optional element of type xsd:string */
	char *TID;	/* optional element of type xsd:string */
	int *trial;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns4__loginModelResponse
#define SOAP_TYPE_ns4__loginModelResponse (55)
/* ns4:loginModelResponse */
struct ns4__loginModelResponse
{
	char *AppUrl;	/* optional element of type xsd:string */
	char *AppVer;	/* optional element of type xsd:string */
	char *Code;	/* optional element of type xsd:string */
	char *Config;	/* optional element of type xsd:string */
	char *ConfigVer;	/* optional element of type xsd:string */
	char *FlashMessage;	/* optional element of type xsd:string */
	char *Message;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns5__BaseMessage
#define SOAP_TYPE_ns5__BaseMessage (73)
/* ns5:BaseMessage */
struct ns5__BaseMessage
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_ns4__TransactionModel
#define SOAP_TYPE_ns4__TransactionModel (24)
/* ns4:TransactionModel */
struct ns4__TransactionModel
{
	char *A;	/* optional element of type xsd:string */
	char *AC;	/* optional element of type xsd:string */
	char *ActDate;	/* optional element of type xsd:string */
	char *AuthCode;	/* optional element of type xsd:string */
	char *BID;	/* optional element of type xsd:string */
	char *CC;	/* optional element of type xsd:string */
	char *CH;	/* optional element of type xsd:string */
	char *CN;	/* optional element of type xsd:string */
	char *CV;	/* optional element of type xsd:string */
	char *CapDate;	/* optional element of type xsd:string */
	char *Code;	/* optional element of type xsd:string */
	char *Drecord;	/* optional element of type xsd:string */
	char *EM;	/* optional element of type xsd:string */
	char *EMVTags;	/* optional element of type xsd:string */
	char *ET;	/* optional element of type xsd:string */
	char *EXPD;	/* optional element of type xsd:string */
	char *FName;	/* optional element of type xsd:string */
	char *FnCode;	/* optional element of type xsd:string */
	int *HostID;	/* optional element of type xsd:int */
	char *KSN;	/* optional element of type xsd:string */
	char *LDate;	/* optional element of type xsd:string */
	char *LTime;	/* optional element of type xsd:string */
	char *MC;	/* optional element of type xsd:string */
	char *MID;	/* optional element of type xsd:string */
	char *MN;	/* optional element of type xsd:string */
	char *MO;	/* optional element of type xsd:string */
	char *MTI;	/* optional element of type xsd:string */
	char *MsgReason;	/* optional element of type xsd:string */
	char *OriginalData;	/* optional element of type xsd:string */
	char *PANEXT;	/* optional element of type xsd:string */
	char *PC;	/* optional element of type xsd:string */
	char *PCC;	/* optional element of type xsd:string */
	char *PEM;	/* optional element of type xsd:string */
	char *PK;	/* optional element of type xsd:string */
	char *PanSeq;	/* optional element of type xsd:string */
	char *PinBlock;	/* optional element of type xsd:string */
	char *RRN;	/* optional element of type xsd:string */
	char *ReversalNo;	/* optional element of type xsd:string */
	char *STAN;	/* optional element of type xsd:string */
	char *SecData;	/* optional element of type xsd:string */
	struct ns4__settlementData *SettlementData;	/* optional element of type ns4:settlementData */
	char *TID;	/* optional element of type xsd:string */
	enum xsd__boolean *isPOS;	/* optional element of type xsd:boolean */
	enum xsd__boolean *isSMS;	/* optional element of type xsd:boolean */
	float *lat;	/* optional element of type xsd:float */
	float *lng;	/* optional element of type xsd:float */
	enum xsd__boolean *pinvalid;	/* optional element of type xsd:boolean */
	char *sig;	/* optional element of type xsd:string */
	char *versions;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__settlementData
#define SOAP_TYPE_ns4__settlementData (74)
/* ns4:settlementData */
struct ns4__settlementData
{
	char *AddAmounts;	/* optional element of type xsd:string */
	int *CRevNo;	/* optional element of type xsd:int */
	int *CrdAmont;	/* optional element of type xsd:int */
	int *CrdRevAmont;	/* optional element of type xsd:int */
	int *CredNO;	/* optional element of type xsd:int */
	int *DAmont;	/* optional element of type xsd:int */
	int *DNo;	/* optional element of type xsd:int */
	int *DRevAmont;	/* optional element of type xsd:int */
	int *DRevNo;	/* optional element of type xsd:int */
	char *MsgAuth;	/* optional element of type xsd:string */
	char *NetAmount;	/* optional element of type xsd:string */
	int *PayNo;	/* optional element of type xsd:int */
	int *PayReverseNo;	/* optional element of type xsd:int */
	char *RedemNo;	/* optional element of type xsd:string */
	struct ns4__ArrayOfTransactionDataList *tdList;	/* optional element of type ns4:ArrayOfTransactionDataList */
};
#endif

#ifndef SOAP_TYPE_ns4__TransactionResponse
#define SOAP_TYPE_ns4__TransactionResponse (27)
/* ns4:TransactionResponse */
struct ns4__TransactionResponse
{
	char *AcDate;	/* optional element of type xsd:string */
	char *AddRespData;	/* optional element of type xsd:string */
	char *AuthCode;	/* optional element of type xsd:string */
	char *CN;	/* optional element of type xsd:string */
	char *Code;	/* optional element of type xsd:string */
	char *DataRec;	/* optional element of type xsd:string */
	char *EMVResponse;	/* optional element of type xsd:string */
	char *FName;	/* optional element of type xsd:string */
	char *LDate;	/* optional element of type xsd:string */
	char *LTime;	/* optional element of type xsd:string */
	char *MID;	/* optional element of type xsd:string */
	char *MTI;	/* optional element of type xsd:string */
	char *Mac;	/* optional element of type xsd:string */
	char *Message;	/* optional element of type xsd:string */
	char *PC;	/* optional element of type xsd:string */
	char *RRN;	/* optional element of type xsd:string */
	char *STAN;	/* optional element of type xsd:string */
	char *SecureData;	/* optional element of type xsd:string */
	enum xsd__boolean *SigRequired;	/* optional element of type xsd:boolean */
	char *TID;	/* optional element of type xsd:string */
	char *Versions;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns4__settlement
#define SOAP_TYPE_ns4__settlement (30)
/* ns4:settlement */
struct ns4__settlement
{
	char *AC;	/* optional element of type xsd:string */
	int *AddAMount;	/* optional element of type xsd:int */
	char *Auth;	/* optional element of type xsd:string */
	char *BID;	/* optional element of type xsd:string */
	char *BT;	/* optional element of type xsd:string */
	int *CNO;	/* optional element of type xsd:int */
	int *CReverseNo;	/* optional element of type xsd:int */
	char *Cdate;	/* optional element of type xsd:string */
	int *CredAmount;	/* optional element of type xsd:int */
	int *CredReversalAmount;	/* optional element of type xsd:int */
	int *DNo;	/* optional element of type xsd:int */
	int *DReverseNo;	/* optional element of type xsd:int */
	int *DebtAmount;	/* optional element of type xsd:int */
	int *DebtReversalAmount;	/* optional element of type xsd:int */
	char *FunCode;	/* optional element of type xsd:string */
	int *HostID;	/* optional element of type xsd:int */
	char *LDate;	/* optional element of type xsd:string */
	char *LTime;	/* optional element of type xsd:string */
	char *MID;	/* optional element of type xsd:string */
	char *MTI;	/* optional element of type xsd:string */
	char *NetAmount;	/* optional element of type xsd:string */
	char *PANEXT;	/* optional element of type xsd:string */
	char *PC;	/* optional element of type xsd:string */
	int *PayNo;	/* optional element of type xsd:int */
	int *PayReverseNo;	/* optional element of type xsd:int */
	char *RN;	/* optional element of type xsd:string */
	char *ReconCurrency;	/* optional element of type xsd:string */
	char *RedemNo;	/* optional element of type xsd:string */
	char *STAN;	/* optional element of type xsd:string */
	char *SecurData;	/* optional element of type xsd:string */
	char *SendDate;	/* optional element of type xsd:string */
	char *TID;	/* optional element of type xsd:string */
	char *Transdate;	/* optional element of type xsd:string */
	char *_USCOREx0038_USCORE1;	/* optional element of type xsd:string */
	char *_USCOREx0039_USCORE0;	/* optional element of type xsd:string */
	struct ns4__ArrayOfTransactionDataList *tdList;	/* optional element of type ns4:ArrayOfTransactionDataList */
};
#endif

#ifndef SOAP_TYPE_ns4__sig
#define SOAP_TYPE_ns4__sig (40)
/* ns4:sig */
struct ns4__sig
{
	int *AC;	/* optional element of type xsd:int */
	char *BID;	/* optional element of type xsd:string */
	char *CN;	/* optional element of type xsd:string */
	char *MID;	/* optional element of type xsd:string */
	char *RRN;	/* optional element of type xsd:decimal */
	char *STAN;	/* optional element of type xsd:string */
	char *TID;	/* optional element of type xsd:string */
	char *sigData;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE___ns1__ExecuteTransaction
#define SOAP_TYPE___ns1__ExecuteTransaction (83)
/* Operation wrapper: */
struct __ns1__ExecuteTransaction
{
	struct _ns1__ExecuteTransaction *ns1__ExecuteTransaction;	/* optional element of type ns1:ExecuteTransaction */
};
#endif

#ifndef SOAP_TYPE___ns1__SendSettlement
#define SOAP_TYPE___ns1__SendSettlement (87)
/* Operation wrapper: */
struct __ns1__SendSettlement
{
	struct _ns1__SendSettlement *ns1__SendSettlement;	/* optional element of type ns1:SendSettlement */
};
#endif

#ifndef SOAP_TYPE___ns1__DBChecker
#define SOAP_TYPE___ns1__DBChecker (91)
/* Operation wrapper: */
struct __ns1__DBChecker
{
	struct _ns1__DBChecker *ns1__DBChecker;	/* optional element of type ns1:DBChecker */
};
#endif

#ifndef SOAP_TYPE___ns1__UpdateSignature
#define SOAP_TYPE___ns1__UpdateSignature (95)
/* Operation wrapper: */
struct __ns1__UpdateSignature
{
	struct _ns1__UpdateSignature *ns1__UpdateSignature;	/* optional element of type ns1:UpdateSignature */
};
#endif

#ifndef SOAP_TYPE___ns1__UploadBatch
#define SOAP_TYPE___ns1__UploadBatch (99)
/* Operation wrapper: */
struct __ns1__UploadBatch
{
	struct _ns1__UploadBatch *ns1__UploadBatch;	/* optional element of type ns1:UploadBatch */
};
#endif

#ifndef SOAP_TYPE___ns1__Login
#define SOAP_TYPE___ns1__Login (103)
/* Operation wrapper: */
struct __ns1__Login
{
	struct _ns1__Login *ns1__Login;	/* optional element of type ns1:Login */
};
#endif

#ifndef SOAP_TYPE___ns1__CheckUpdate
#define SOAP_TYPE___ns1__CheckUpdate (107)
/* Operation wrapper: */
struct __ns1__CheckUpdate
{
	struct _ns1__CheckUpdate *ns1__CheckUpdate;	/* optional element of type ns1:CheckUpdate */
};
#endif

#ifndef SOAP_TYPE___ns1__ReloadService
#define SOAP_TYPE___ns1__ReloadService (111)
/* Operation wrapper: */
struct __ns1__ReloadService
{
	struct _ns1__ReloadService *ns1__ReloadService;	/* optional element of type ns1:ReloadService */
};
#endif

#ifndef SOAP_TYPE___ns1__GetLogFile
#define SOAP_TYPE___ns1__GetLogFile (115)
/* Operation wrapper: */
struct __ns1__GetLogFile
{
	struct _ns1__GetLogFile *ns1__GetLogFile;	/* optional element of type ns1:GetLogFile */
};
#endif

#ifndef SOAP_TYPE___ns1__GetLog
#define SOAP_TYPE___ns1__GetLog (119)
/* Operation wrapper: */
struct __ns1__GetLog
{
	struct _ns1__GetLog *ns1__GetLog;	/* optional element of type ns1:GetLog */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (120)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (121)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (123)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (126)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (127)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__byte
#define SOAP_TYPE_xsd__byte (12)
typedef char xsd__byte;
#endif

#ifndef SOAP_TYPE_xsd__unsignedByte
#define SOAP_TYPE_xsd__unsignedByte (13)
typedef unsigned char xsd__unsignedByte;
#endif

#ifndef SOAP_TYPE_xsd__ID
#define SOAP_TYPE_xsd__ID (14)
typedef char *xsd__ID;
#endif

#ifndef SOAP_TYPE_xsd__IDREF
#define SOAP_TYPE_xsd__IDREF (15)
typedef char *xsd__IDREF;
#endif

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (16)
typedef char *xsd__anyURI;
#endif

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (17)
typedef char *xsd__decimal;
#endif

#ifndef SOAP_TYPE_xsd__duration
#define SOAP_TYPE_xsd__duration (18)
typedef char *xsd__duration;
#endif

#ifndef SOAP_TYPE_ns3__char
#define SOAP_TYPE_ns3__char (19)
typedef int ns3__char;
#endif

#ifndef SOAP_TYPE_ns3__duration
#define SOAP_TYPE_ns3__duration (20)
typedef char *ns3__duration;
#endif

#ifndef SOAP_TYPE_ns3__guid
#define SOAP_TYPE_ns3__guid (21)
typedef char *ns3__guid;
#endif

#ifndef SOAP_TYPE_ns6__StreamBody
#define SOAP_TYPE_ns6__StreamBody (22)
typedef struct xsd__base64Binary ns6__StreamBody;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ExecuteTransaction(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ExecuteTransaction *ns1__ExecuteTransaction, struct _ns1__ExecuteTransactionResponse *ns1__ExecuteTransactionResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SendSettlement(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__SendSettlement *ns1__SendSettlement, struct _ns1__SendSettlementResponse *ns1__SendSettlementResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DBChecker(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__DBChecker *ns1__DBChecker, struct _ns1__DBCheckerResponse *ns1__DBCheckerResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UpdateSignature(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__UpdateSignature *ns1__UpdateSignature, struct _ns1__UpdateSignatureResponse *ns1__UpdateSignatureResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UploadBatch(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__UploadBatch *ns1__UploadBatch, struct _ns1__UploadBatchResponse *ns1__UploadBatchResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__Login(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__Login *ns1__Login, struct _ns1__LoginResponse *ns1__LoginResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CheckUpdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckUpdate *ns1__CheckUpdate, struct _ns1__CheckUpdateResponse *ns1__CheckUpdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ReloadService(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ReloadService *ns1__ReloadService, struct _ns1__ReloadServiceResponse *ns1__ReloadServiceResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLogFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetLogFile *ns1__GetLogFile, struct _ns1__GetLogFileResponse *ns1__GetLogFileResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetLog *ns1__GetLog, struct _ns1__GetLogResponse *ns1__GetLogResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of BM_C_SoapStub.h */
